### ISSUE TITLE
CRLF used for line endings, regardless of line endings used in source

### ISSUE THREAD

**Issue by acidus99** [makew0rld/md2gemini#48]
md2gemini is hardcoded to use CRLF for line endings, regardless of the line endings used by the source file:

```
$ file *
foo.md: ASCII text, with very long lines (1439)
$ md2gemini -w foo.md 
$ file *
foo.gmi: ASCII text, with very long lines (1439), with CRLF line terminators
foo.md:  ASCII text, with very long lines (1439)
```

Expectation: The line ending character(s) in the output of md2gemini should be the same as the line ending character(s) of the source file.
Actual: md2gemini generates output with CRLF line endings regardless of the source.

This is a little annoying since it requires users to running another tool like `dos2unix` to undo this. That also requires the user to figure out what the original line endings were and convert if needed.

**Comment by makew0rld** [comment]
This is by design, for compatibility. In regards to #50, I think switching to only LF makes more sense than having the output vary by OS.
